### ISSUE TITLE
It looks like W2PUserChoiceObject doesn't support Dark Mode

### ISSUE THREAD

**Issue by jflow** [HsiangHo/Welcome2ProjectKit#1]
When on Mojave in Dark Mode the W2PUserChoiceObject(s) do not appear. They are clickable but unreadable. Switch to Light Mode and they appear as expected. I can understand with the images if they are not set to be used in Dark Mode, but it looks like your custom label class doesn't handle it either. 

I am going to dig in and see what I can find. 

The project looks very interesting!

**Comment by HsiangHo** [comment]
I've fixed it. Now it's compatible with dark mode.@jflow
